services:
    homeassistant:
        image: lscr.io/linuxserver/homeassistant
        container_name: homeassistant
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        cap_add:
            - NET_ADMIN
            - NET_RAW
        volumes:
            - /home/gordon/proj/homeassistant/data:/config
            - /var/run/dbus:/var/run/dbus:ro
        restart: unless-stopped

    mosquitto:
        image: eclipse-mosquitto
        container_name: mosquitto
        volumes:
            - /home/gordon/proj/mosquitto:/mosquitto
            - /home/gordon/proj/mosquitto/data:/mosquitto/data
            - /opt/mosquitto/log:/mosquitto/log
        ports:
            - 1883:1883
            - 9001:9001  
        restart: unless-stopped
